### ISSUE TITLE
哥。。。为什么会没有统计调用时间和次数

### ISSUE THREAD

**Issue by kouyusanpi** [zhongxig/dubbo-d-monitor#1]
我使用AntsMonitorServer  本地启动的，测试也都在本地，redis mysql 都连接上了，但就是没有统计数据出来，服务和消费者都发现了

**Comment by kouyusanpi** [comment]
忘记说了，是 mysql 版

**Comment by zhongxig** [comment]
zk 配置是否正确，在同个局域网内同个zk下进行 消费，间隔一分钟会有数据统计到DubboMonitorService 的collect 方法，你可以断点 试下

**Comment by zhongxig** [comment]
抱歉，今天 合并代码到master上时，发现 配置文件的 dubbo.registry.address 命名沿用老的，导致 zk地址为空，现在已经修复，且 mysql版本后续在 master上开发
