### ISSUE TITLE
如果有多个DUBBO项目，就是用了多个端口

### ISSUE THREAD

**Issue by R1hug0** [zhongxig/dubbo-d-monitor#2]
要怎么配置呢，能写在一个配置里面吗

**Comment by R1hug0** [comment]
![123](https://cloud.githubusercontent.com/assets/8827342/17352271/e0882b72-5967-11e6-8590-33f034fe918b.png)
mvn编译报此错误怎么弄

**Comment by zhongxig** [comment]
是使用 “ mvn clean package -Dmaven.test.skip -U ”  命令进行 打包编译的么？

**Comment by R1hug0** [comment]
嗯MVN打包OK了,我换了阿里的私服地址 ,要监控的DUBBO服务怎么添加呢.

**Comment by R1hug0** [comment]
@zhongxig   大兄可否搞个使用说明呢. 搭起来了,怎么监控需要服务

**Comment by zhongxig** [comment]
请 参考 《四、使用帮助》，里面有说如何 配置 zk，进行监控

**Comment by R1hug0** [comment]
com.ants.monitor.bean.MonitorConstants的initEcsMap方法，在内存中存入自定义线上ip地址和测试环境ip地址。 是这个吗,我如下写了,好象没起作用,
    public static void initEcsMap(){

        ecsTestMap.put("172.30.1.115", "172.30.1.115");
        ecsTestMap.put("172.30.1.114", "172.30.1.114");
        ecsTestMap.put("172.30.1.100", "172.30.1.100");

    }

**Comment by zhongxig** [comment]
ecsTestMap 我自己写的时候 是 内外网对应，例如ecsTestMap.put("10.10.1.1","172.30.1.100");

public static void initEcsMap(){
        //todo 自定义初始化上述map。将ip放置在内存中。
        ecsMap.put("10.0.0.1","测试服务器");

        ecsBiMap.put("10.0.0.1","192.xxx.x0.xx");
        ecsBiMap.put("10.0.0.2","192.xxx.x1.xx");

        ecsTestMap.put("10.0.0.2","192.xxx.x1.xx");
    }

**Comment by R1hug0** [comment]
如上写好象没有启作用,
初始化信息application.properties的zookeeper.address = 127.0.0.1:2181 # 此zk地址是不是填写被监控的zookeeper,如果有多个zk要监控就写多个吗(如果是怎么写)?然后ecs*Map定义的主机是注册到这里填写的zk上面,监控再显示所以连接此zk的主机,不知道是不是这理解的呢.

**Comment by zhongxig** [comment]
若多个，则用 逗号隔开
zookeeper.address = 127.0.0.1:2181,127.0.0.2:2181,127.0.0.3:2181，
ecs*Map定义的主机 是注册到zk 上的主机，人为的分类罢了，我把这个写到 readme 吧

**Comment by R1hug0** [comment]
哈哈,明白了,我刚用|管道符, 多谢大神.

**Comment by R1hug0** [comment]
大神,配置我确实加了3个,但是只显示一个zk上的内容,

**Comment by zhongxig** [comment]
这个项目，目前是
1. 没有测试过连接 例如应用1接入zkA，应用2接入zkB。是不支持多zk，各自为阵营
2. 我以为你是 应用1 连接 zkA,zkB。应用2连接 zkA,zkB。即 zk集群，是支持集群查看的。

**Comment by R1hug0** [comment]
好滴,明白了, 小小愿望希望可以加入多zk监控 :+1:
