### ISSUE TITLE
mysql版的数据量大了后，怎么处理，有做分表的设计吗

### ISSUE THREAD

**Issue by cnprinces** [zhongxig/dubbo-d-monitor#3]
mysql版的数据量大了后，怎么处理，有做分表的设计吗

**Comment by zhongxig** [comment]
目前是mysql存储30天的数据，超过30天的数据默认用户不关心，定时器定时删除。暂时没考虑所有数据都保留，量太大了～～～

**Comment by cnprinces** [comment]
假如采用MongoDB的话 是不是可以解决这个问题~

**Comment by zhongxig** [comment]
没试过，不过 mongo的特性 应该会对这个支持比较好，刚开始，我使用redis 作为nosql数据库存储，发现占用过大，然后 才采用 mysql作为持久层，redis 缓存～
