### ISSUE TITLE
是否需要在dubbo配置文件中增加属性？

### ISSUE THREAD

**Issue by huaijinwoyu** [zhongxig/dubbo-d-monitor#5]
RT，是否需要在dubbo配置中增加dubbo:monitor 这个属性呢？我看首页没有介绍

**Comment by zhongxig** [comment]
这个项目中不需要，它主动实现了 监控中心接口~

如果其他 提供者或者消费者，
1. zk 主动分发 监控中心地址
`
<dubbo:monitor protocol="registry"/>`
这么写即可，zk会 自动分配监控中心的ip给到 dubbo应用~
2. 直连监控中心
`<dubbo:monitor address="10.20.130.230:12080"/>`

**Comment by huaijinwoyu** [comment]
好的，谢谢，我去试试。
