### ISSUE TITLE
项目启动报错问题

### ISSUE THREAD

**Issue by huaijinwoyu** [zhongxig/dubbo-d-monitor#6]
项目现在启动报错，我之前在application.properties 改成了自己的配置，然后在META-INF/autoconf下面的auto-config.xml也替换了，现在启动报错。

SEVERE: The web application [] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Nov 07, 2016 10:46:50 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Nov 07, 2016 10:46:50 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.

**Comment by zhongxig** [comment]
1. 如果是 jetty 启动：跟META-INF/autoconf 无关，看下 application.properties 中：
jdbc 的 数据库 配置是否正确

2. 如果是 tomcat 启动：跟 autoconfig 生成的 antx.properties 里面配置有关，或者直接看 tomcat根目录下的webapps里面的 ROOT/WEB-INF/classes/application.properties

**Comment by huaijinwoyu** [comment]
上面的问题解决了，现在遇到了新的问题，Redis配置数据库，我的redis是默认的没有分库
`redis://ants-monitor:123456@127.0.0.1:6379/2 #此处为redis数据库 密码@ip:host/db号`  我不知道该写那个db号

**Comment by zhongxig** [comment]
redis默认有db0~db15

因此 你可以通过 redis-cli 命令 进redis 进行查看。如果 是默认没有分库——那你就 用默认的 0 吧！
ps：db数量是在 redis根目录下的 redis.conf 中的 databases 变量控制，默认是 16

**Comment by huaijinwoyu** [comment]
`redis://ants-monitor:**123456**@127.0.0.1:6379/2 `  密码我有特殊字符，比如有@符号，这个应该会连接错误吧

**Comment by huaijinwoyu** [comment]
` redis.host  = redis://密码@IP地址:6379/2  `  是这样吗?

**Comment by zhongxig** [comment]
redis.host = redis://随便一个名称:密码@IP地址:6379/2

**Comment by huaijinwoyu** [comment]
问题找到了，我的redis密码有特殊字符，需要URL编码下，然后放进去才能启动成功，建议在初始化redis之前把redis.host编码下。

**Comment by huaijinwoyu** [comment]
Redis不报错了，现在错误信息不知道是什么了，只有下面的这些提示。

`SEVERE: Context [] startup failed due to previous errors
Nov 08, 2016 1:25:09 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Nov 08, 2016 1:25:09 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Nov 08, 2016 1:25:09 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.
Nov 08, 2016 1:25:09 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /usr/local/tomcat_8082/webapps/ROOT.war has finished in 13,502 ms
Nov 08, 2016 1:25:09 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8082"]
Nov 08, 2016 1:25:09 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-10006"]
Nov 08, 2016 1:25:09 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 13655 ms`

**Comment by zhongxig** [comment]
看下 jdbc 的配置

**Comment by huaijinwoyu** [comment]
JDBC配置我除了改IP地址外，其他的没动过呢。
这个是配置信息
`jdbc.url=jdbc:mysql://120.24.68.15:6033/dubbo_monitor?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true`


这个是错误信息 
`log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
十一月 08, 2016 4:35:07 下午 org.apache.catalina.core.StandardContext startInternal
严重: One or more listeners failed to start. Full details will be found in the appropriate container log file
十一月 08, 2016 4:35:07 下午 org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
信息: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [355] milliseconds.
十一月 08, 2016 4:35:07 下午 org.apache.catalina.core.StandardContext startInternal
严重: Context [] startup failed due to previous errors
十一月 08, 2016 4:35:07 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
严重: The web application [] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
十一月 08, 2016 4:35:07 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
严重: The web application [] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
十一月 08, 2016 4:35:07 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
严重: The web application [] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak.
十一月 08, 2016 4:35:07 下午 org.apache.catalina.startup.HostConfig deployWAR
信息: Deployment of web application archive D:\software\apache-tomcat-7.0.68_2\webapps\ROOT.war has finished in 12,439 ms`

**Comment by zhongxig** [comment]
你要 在自己的mysql 数据库 执行 sql 代码，然后 properties 里面 配置 你自己的mysql ip和chema，密码也是自己的mysql 密码

**Comment by huaijinwoyu** [comment]
我尝试把数据库连接直接写在application-mybatis中，现在没有报mysql的错误。

但是还有一个别的错误 

`十一月 09, 2016 11:39:49 上午 org.apache.catalina.core.StandardContext startInternal
严重: One or more listeners failed to start. Full details will be found in the appropriate container log file
十一月 09, 2016 11:39:50 上午 org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
信息: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [1,519] milliseconds.
十一月 09, 2016 11:39:50 上午 org.apache.catalina.core.StandardContext startInternal
严重: Context [] startup failed due to previous errors`

**Comment by zhongxig** [comment]
错误信息过少，无法判断。
启动错误 基本都会打印出来，你好好看下哈~

**Comment by gf76866908** [comment]
我想知道  最后你这个怎么解决的  我也遇到这个 问题了
